name: Test

on: [push, pull_request]

jobs:
  build:
    runs-on: ${{ matrix.os }}
    strategy:
      fail-fast: false
      matrix:
        python-version: [3.6, 3.7, 3.8, pypy3]
        os: [ubuntu-latest, macos-latest, windows-latest]
        exclude:
          # Exclude this failing combination, as PyPy is not yet supported
          - python-version: pypy3
            os: windows-latest

    steps:
      - name: Checkout repository
        uses: actions/checkout@v1

      - name: Set up Python ${{ matrix.python-version }}
        uses: actions/setup-python@v1
        with:
          python-version: ${{ matrix.python-version }}

      - name: Install dependencies
        run: |
          python -m pip install --upgrade pip wheel setuptools
          pip install --upgrade cython pytest

      - name: Install dependencies (mypy)
        if: matrix.python-version != 'pypy3'
        run: |
          pip install --upgrade mypy

      - name: Install project
        run: |
          python setup.py transpile_cython --force build_ext
          pip install -e .

      - name: Type check test code using mypy
        if: matrix.python-version != 'pypy3'
        run: |
          mypy tests

      - name: Run unit tests using pytest
        run: |
          pytest tests
